services:
  workflows-demo-app:
    build: .
#    depends_on:
#      - workflows-db
    ports:
      - "8080:8080"

#  workflows-db:
#    image: mysql
#    container_name: workflows-demo-db
#    restart: always
#    ports:
#      - "3309:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: docker
#    volumes:
#      - ./mysql-data:/var/lib/mysql
